In [ ]:
import numpy as np
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving emnist-letters-train.csv to emnist-letters-train.csv


In [ ]:
df = pd.read_csv("emnist-letters-train.csv",header = None)
df.head()

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  778  \
0   23    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    7    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2   16    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3   15    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4   23    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   779  780  781  782  783  784  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 785 columns]

In [ ]:
df.columns

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            775, 776, 777, 778, 779, 780, 781, 782, 783, 784],
           dtype='int64', length=785)

In [ ]:
xa =df.drop(labels= 0, axis=1)
xa

1    2    3    4    5    6    7    8    9    10   ...  775  776  777  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 784 columns]

In [ ]:
ya =df[[0]]
ya

0
0      23
1       7
2      16
3      15
4      23
...    ..
88795   1
88796  21
88797   1
88798  23
88799  12

[88800 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
norm = MinMaxScaler().fit(xa)
xa_norm = norm.transform(xa)

In [ ]:
np.shape(xa_norm)

(88800, 784)

In [ ]:
ones = np.ones((len(xa_norm),1),dtype = float)

In [ ]:
xa_norms =np.concatenate((ones,xa_norm),axis = 1)

In [ ]:
np.shape(xa_norms)

(88800, 785)

In [ ]:
print(xa_norms)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
def sigmoid(theta,X):
  Z = np.dot(X,theta)
  h = 1/(1+np.exp(-Z))
  return h

In [ ]:
def cost(theta,X,Y):
  cost0 = np.dot(np.transpose(Y),np.log(sigmoid(theta,X)))
  cost1 =  np.dot(np.transpose(1-Y),np.log(1-sigmoid(theta,X)))
  totalcost = -((cost1 + cost0))/len(Y) 
  return totalcost

In [ ]:
some_digit = xa_norm[1]

In [ ]:
some_digit_image = some_digit.reshape(28,28)

In [ ]:
plt.imshow(some_digit_image,cmap = matplotlib.cm.binary,interpolation = "nearest")

In [ ]:
m = len(ya)
m

In [ ]:
a =np.ones((m,1),dtype = int)
a

In [ ]:
a =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 1:
    a[i] = 1
  else:
    a[i] = 0
a


In [ ]:
b =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 2:
    b[i] = 1
  else:
    b[i] = 0
b

In [ ]:
c =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 13:
    c[i] = 1
  else:
    c[i] = 0
c



In [ ]:
d =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 4:
    d[i] = 1
  else:
    d[i] = 0
d



In [ ]:
e =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.iloc[i].iat[0] == 5:
    e[i] = 1
  else:
    e[i] = 0
e


In [ ]:
f =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 6:
    f[i] = 1
  else:
    f[i] = 0
f



In [ ]:
g =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 7:
    g[i] = 1
  else:
    g[i] = 0
g



In [ ]:
h =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 8:
    h[i] = 1
  else:
    h[i] = 0
h


In [ ]:
I=np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 9:
    I[i] = 1
  else:
    I[i] = 0
I


In [ ]:
j =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 10:
    j[i] = 1
  else:
    j[i] = 0
j


In [ ]:
k =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 11:
    k[i] = 1
  else:
    k[i] = 0
k



In [ ]:
l =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 12:
    l[i] = 1
  else:
    l[i] = 0
l


In [ ]:
M = np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 13:
    M[i] = 1
  else:
    M[i] = 0
M




In [ ]:
n =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 14:
    n[i] = 1
  else:
    n[i] = 0
n



array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
o =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 15:
    o[i] = 1
  else:
    o[i] = 0
o


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
p =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 16:
    p[i] = 1
  else:
    p[i] = 0
p


array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
q =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 17:
    q[i] = 1
  else:
    q[i] = 0
q


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
r =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 18:
    r[i] = 1
  else:
    r[i] = 0
r


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
s =np.ones((m,1),dtype = int)
for i in range(m):
  if ya.loc[i].iat[0] == 19:
    s[i] = 1
  else:
    s[i] = 0
s

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
t =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 20:
    t[i] = 1
  else:
    t[i] = 0
t

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
u =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 21:
    u[i] = 1
  else:
    u[i] = 0
u

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
v =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 22:
    v[i] = 1
  else:
    v[i] = 0
v

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
w =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 23:
    w[i] = 1
  else:
    w[i] = 0
w

In [ ]:
x =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 24:
    x[i] = 1
  else:
    x[i] = 0
x

In [ ]:
y =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 25:
    y[i] = 1
  else:
    y[i] = 0
y

In [ ]:
z =np.ones((m,1),dtype = int)
for i in range(0,m):
  if ya.loc[i].iat[0] == 26:
    z[i] = 1
  else:
    z[i] = 0
z

In [ ]:
y1 = np.concatenate((a,b,c,d,e,f,g,h,I,j,k,l,M,n,o,p,q,r,s,t,u,v,w,x,y,z),axis = 1) 
np.shape(y1)

(88800, 26)

In [ ]:
theta = np.zeros([xa_norms.shape[1], y1.shape[1]])
theta

In [ ]:
def log_reg_model(X, Y, theta, alpha,iteration):
    m = len(X)
    n =X.shape[1]
    costlist = []
    theta = np.zeros((n, Y.shape[1]),dtype = float)
    for i in range(0, iteration):
        for j in range(0, 25):
             h = sigmoid(theta[:,j], X)
             error = h-Y[:,j]
             theta[:, j] -= (alpha/m) * (np.dot(X.transpose(),error))
             c =cost(X, Y[:, j], theta[:,j])
             costlist.append(c)
    return theta, costlist


In [ ]:
theta,costlist = log_reg_model(xa_norms, y1, theta, 0.1, 1500)

In [99]:
for j in range(0,25):
  h = sigmoid(theta[:,j], xa_norms)

In [104]:
np.amax(h)

0.9802427642460767

In [ ]:
ind = h.argmax()
ind

In [ ]:
index = np.where(h == np.amax(h))
index

In [ ]:
theta = pd.DataFrame(theta)
print(theta)